name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run build shell script
        run: ci/build-app.sh
      
      - name: Test
        run: ci/unit-test-app.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  lint:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
    
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
